paths:
  # [GET] /
  /:
    get:
      tags:
        - default
      summary: Dummy response
      responses:
        200:
          description: 'OK'
        500:
          description: 'Server Error'
